---
- name: "Pull backend image from DockerHub"
  command: docker pull {{ backend_image }}
  register: pull_backend
  changed_when: "'Downloaded' in pull_backend.stdout"

- name: "Pull frontend image from DockerHub"
  command: docker pull {{ frontend_image }}
  register: pull_frontend
  changed_when: "'Downloaded' in pull_frontend.stdout"
