# apiVersion: v1
# kind: Service
# metadata:
#   name: rag-backend
# spec:
#   selector:
#     app: rag-backend
#   ports:
#     - port: 8000
#       targetPort: 8000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rag-frontend
# spec:
#   selector:
#     app: rag-frontend
#   ports:
#     - port: 8501
#       targetPort: 8501
apiVersion: v1
kind: Service
metadata:
  name: rag-backend
spec:
  selector:
    app: rag-backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-frontend
spec:
  selector:
    app: rag-frontend
  ports:
    - port: 8501
      targetPort: 8501
